### ISSUE TITLE
Cannot call value of non-function type 'FileType?'

### ISSUE THREAD

**Issue by RabbitMC** [nvzqz/FileKit#52] opened 2017-10-23 14:14 UTC
Hi,
I'm getting a compiler error when building my macOS app using FileKit integrated with Cocoapods.

The app is for macOS 10.13. I'm using Xcode 9.0.1, Cocoapods and FileKit 4.0.1 (5.0.0 was not available over Cocoapods)

If I want to compile the I getting this error:

`Cannot call value of non-function type 'FileType?' ` in 

```
extension File: CustomStringConvertible {

    // MARK: - CustomStringConvertible

    /// A textual representation of `self`.
    public var description: String {
        return String(describing: type(of: self)) + "('" + path.description + "')"
    }

}
```

**Comment by phimage** [comment] 2017-11-09 09:07
@RabbitMC You can get 5.0.0 with cocoapod, just put the git URL in Podfile (and you also specify commit or branch or tag)

I make a pod try FileKit without any issue when compiling using Xcode9.1

You want to use swift4 or swift3?

**Comment by RabbitMC** [comment] 2017-11-14 14:44
hey @phimage,

thanks for reply. 

>You can get 5.0.0 with cocoapod, just put the git URL in Podfile

I will get v5.0.0 over the git URL. Thanks for the hint.

>You want to use swift4 or swift3?

Swift 4

**Comment by kivenZheng** [comment] 2018-01-10 03:45
It has this problem when when compiling using Xcode9.2

**Comment by phimage** [comment] 2018-01-13 21:34
@kivenZheng please describe your issue, useless to speak without adding any information

**Comment by phimage** [comment] 2018-01-17 08:27
close as duplicate of #51

**Closed by phimage** 2018-01-17 08:27 UTC
